### ISSUE TITLE
Open issues pnorman's version

### ISSUE THREAD

**Issue by roelderickx** [roelderickx/ogr2osm#3]
- [ ] pnorman/ogr2osm#56 ogr2osm misses some multipolygons in US National Park boundary shapefile
- [ ] pnorman/ogr2osm#47 Multipolygon without inner do not assign tags
- [x] pnorman/ogr2osm#46 Not returning osm file in Mac
  Possible duplicate of pnorman/ogr2osm#24 and pnorman/ogr2osm#9, won't fix without further information
- [x] pnorman/ogr2osm#45 Making main flow importable
  See README.md for more information
- [x] pnorman/ogr2osm#44 Clarify the difference between rounding digits and significant digits
  Added better description for both parameters
- [x] pnorman/ogr2osm#42 add bounding box information
  `--add-bounds` parameter added
- [x] pnorman/ogr2osm#40 Inconsistent or missing use of addparent.
- [ ] pnorman/ogr2osm#36 python killed
- [x] pnorman/ogr2osm#31 Request for duplicated points
  See `get_unique_node_identifier` translation method.
- [ ] pnorman/ogr2osm#28 Shared borders represented as duplicated ways.
- [x] pnorman/ogr2osm#24 Error when trying to skip an object in translation
  Duplicate of pnorman/ogr2osm#9
- [ ] pnorman/ogr2osm#22 Switch encoding testcases to KML
- [ ] pnorman/ogr2osm#19 Memory error
- [x] pnorman/ogr2osm#18 syntax error bug
  Not applicable as it is related to a python version not supported in this fork
- [x] pnorman/ogr2osm#15 utf-8 encoding xml output
  There is no good reason to fix this, a custom DataWriter class can be inherited from DataWriterBase to obtain the desired result
- [ ] pnorman/ogr2osm#14 Pass options to translation modules enhancement
- [x] pnorman/ogr2osm#9 filterTags not returning bug
  Returning None in filter_tags will drop the object

**Comment by roelderickx** [comment]
pnorman#56
---
@mr-greenjeans +1 for the completeness of your bug report and the investigation you have done already. Thanks!
You correctly identified a bug and it will be fixed in the next version, which will be in this fork since maintenance has ceased on pnorman's version. I will think about a good way to implement the fix, your patch is technically correct but it is not the most elegant solution.

**Comment by roelderickx** [comment]
pnorman#47
---
@joaokho After closer inspection this turns out to be the same issue as above. Thanks for reporting!

**Comment by roelderickx** [comment]
pnorman#22
---
I am not sure if the encoding can be detected for any ogr datasource, if it is not UTF-8 it must be specified by the encoding parameter. Ogr2osm will then try to interpret the file with the given encoding, it is up to the user to know or guess how the source file is encoded.
Even though the standard for shapefiles is Latin-1 it is possible to create such a file with any other encoding. However, for KML files this is not possible, the driver included in GDAL can only handle UTF-8 no matter how the encoding is defined on the first line.
Because human-readable source files are preferable over binary shapefiles and KML is not an option, the encoding testcases have been replaced by geojson files, for which GDAL accepts any encoding.

**Comment by grischard** [comment]
Hey, I'd given up hope on some of these. Many thanks, @roelderickx !!
